name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up MongoDB
      run: sudo apt-get install mongodb-server && sudo systemctl start mongodb
    - name: Run
      run: sbt run -DgithubSecrets.personalAccessToken=${{ secrets.GITHUB_TOKEN }}
